trigger check for files in critical path

diff --git a/.github/workflows/threadsafe-check.yml b/.github/workflows/threadsafe-check.yml
--- a/.github/workflows/threadsafe-check.yml
+++ b/.github/workflows/threadsafe-check.yml
@@ -14,4 +14,23 @@ jobs:
                   fetch-depth: 0
 
             - name: Check for modified files
-              run: 
+              id: changed_files
+              run: |
+                echo "changed_files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
+
+            - name: Verify threadsafety acknowledgement
+              run: |
+                CHANGED_FILES=${{ steps.changed_files.outputs.changed_files }}
+                # Check if changed files are in snowpark/_internal, snowpark/mock, or snowpark/*.py. We exclude snowpark/modin in this check.
+                if echo "$CHANGED_FILES" | grep -qE '(src/snowflake/snowpark/_internal|src/snowflake/snowpark/mock|src/snowflake/snowpark/[^/]+\.py)'; then
+                    echo "Checking PR description for thread-safety acknowledgment..."
+                    if [[ ${{ github.event.pull_request.body }} != *"[x] I acknowledge that I have ensured my changes to be thread-safe"* ]]; then
+                        echo "Thread-safety acknowledgment not found in PR description."
+                        echo "Please acknowledge the threadsafety implications of your changes by adding '[x] I acknowledge that I have ensured my changes to be thread-safe' to the PR description."
+                        exit 1
+                    else
+                        echo "Thread-safety acknowledgment found in PR description."
+                    fi
+                else
+                    echo "No critical files modified; skipping threadsafety check."
+                fi
